# Arbitrary Tello command:
string cmd
---
# Initial response code:
uint8 OK=1                    # Command sent
uint8 ERROR_NOT_CONNECTED=2   # Can't communicate with drone
uint8 ERROR_BUSY=3            # There's already an active command
uint8 rc
